name: update-applist

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *" # run every hour

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute update script
        id: update_script
        run: |
          python update.py

      - name: Sync changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          commit_message: 'Automatic applist update | ${{ steps.update_script.outputs.COMMIT_MESSAGE }}'
          file_pattern: 'data/*.json'